
const PatientModel = () =>
{
    var a = {
        patid:"",
        patcode:"",
        name:"",
        nameunsiger:"",
        birthday:"",
        birthyear:"",
        age:"",
        phonenumber:"",
        email:"",
        agecode:"",
        sexcode:"",
        sexname:"",
        jobcode:"",
        nationcode:"",
        nationNatycode:"",
        religioncode:"",
        village:"",
        citycode:"",
        districtcode:"",
        wardscode:"",
        addresworkplace:"",
        barcode:"",
        relationcode:"",
        ischildren:"",
        parentname:"",
        findcontent:"",
        patientHi:"",
        note:"",
        attributes:"",
        datalog:"",
        mmyys:"",
        yyyy:"",
        siterf:"",
        active:"",
        usercr:"",
        timecr:"",
        userup:"",
        timeup:"",
        computer:"",
        mac:"",
    }
}
export default PatientModel