
const RegisterModel = () =>
{
    var a = {
        rowsid :"",
        linkid :"",
        indepartmentid:"",
        medexacode:"",
        medexaname:"",
        patcode:"",
        doctorcode:"",
        registerdate:"",
        objectcode :"",
        objectname :"",
        addressfull:"",
        phonenumber :"",
        done :"",
        ispatientnew:"", 
        patienttype :"",
        placetransfercode:"", 
        placeIntrocode :"",
        pricecode:"",
        discountcode:"",
        reson :"",
        active:"",     
        note:"",
        attributes:"",
        datalog:"",
        mmyys:"",
        yyyy:"",
        siterf:"",
        active:"",
        usercr:"",
        timecr:"",
        userup:"",
        timeup:"",
        computer:"",
        mac:"",
    }
}
export default RegisterModel
